[variables]
NIXPACKS_JDK_VERSION = "17"

[phases.build]
cmds = ["chmod +x ./mvnw", "./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/ExpenseTracker-0.0.1-SNAPSHOT.jar"
