-- Schema for ExpenseTracker application with OOP structure
-- Using JPA auto-generation instead of manual schema
-- This file is kept for reference but tables are created by Hibernate

-- The following tables will be auto-generated by JPA:
-- 1. transaction (base table with id, description)
-- 2. expense (joined table with transaction, adds amount, date, location, category_id, user_id)
-- 3. app_user (id, name, email)
-- 4. category (id, name)

-- JPA inheritance strategy JOINED creates:
-- - transaction table with common fields
-- - expense table that joins with transaction table
-- This demonstrates proper OOP inheritance in database design
